TeapotBaseUserBundle_login:
    pattern:   /login/
    defaults:  { _controller: TeapotBaseUserBundle:Security:login }
TeapotBaseUserBundle_signup:
    pattern:   /signup/
    defaults:  { _controller: TeapotUserBundle:Registration:signup }
TeapotBaseUserBundle_forgotPassword:
    pattern:   /forgot-password/
    defaults:  { _controller: TeapotBaseUserBundle:Account:forgotPassword }
TeapotBaseUserBundle_resetPassword:
    pattern:   /reset-password/
    defaults:  { _controller: TeapotBaseUserBundle:Account:resetPassword }
TeapotBaseUserBundle_login_check:
    pattern:   /login-check/
TeapotBaseUserBundle_logout:
    pattern:   /logout/
TeapotBaseUserBundle_settings:
    pattern:   /u/{userSlug}-{userId}/settings/
    defaults: { _controller: TeapotUserBundle:Profile:settings }
    requirements:
        userSlug: "[^\/]+"
        userId: \d+
TeapotBaseUserBundle_profile:
    pattern:   /u/{userSlug}-{userId}/
    defaults: { _controller: TeapotUserBundle:Profile:index }
    requirements:
        userSlug: "[^\/]+"
        userId: \d+

TeapotBaseUserBundle_setDefaultImage:
    pattern: /u/set-image/{imageId}/
    defaults: { _controller: TeapotUserBundle:User:setDefaultImage }

TeapotBaseUserBundle_addImage:
    pattern: /u/add-image/
    defaults: { _controller: TeapotUserBundle:User:addImage }
    requirements:
        _method: POST

TeapotBaseUserBundle_setDescription:
    pattern: /u/set-description/
    defaults: { _controller: TeapotUserBundle:User:setDescription }
    requirements:
        _method: POST

TeapotBaseUserBundle_setSettings:
    pattern: /u/set-settings/
    defaults: { _controller: TeapotUserBundle:User:setSettings }
    requirements:
        _method: POST