# Flag Controller
ForumFlagDelete:
    pattern: /flag/delete/{flagId}/
    defaults: { _controller: TeapotForumBundle:Flag:delete }

ForumFlagIgnore:
    pattern: /flag/ignore/{flagId}/
    defaults: { _controller: TeapotForumBundle:Flag:ignore }

# Board Controller
ForumNewBoard:
    pattern:  /new-board/
    defaults: { _controller: TeapotForumBundle:Board:new }

ForumNewTopicWithoutBoard:
    pattern:  /new-topic/
    defaults: { _controller: TeapotForumBundle:Topic:new }

ForumListBoards:
    pattern: /boards/
    defaults: { _controller: TeapotForumBundle:Board:list }

ForumAdminPermissionsWithGroup:
    pattern: /admin/permissions/{groupId}/
    defaults: { _controller: TeapotForumBundle:Admin:Permissions }

ForumAdminPermissions:
    pattern: /admin/permissions/
    defaults: { _controller: TeapotForumBundle:Admin:Permissions }

ForumNewBoardInBoard:
    pattern:  /{boardSlug}/new-board/
    defaults: { _controller: TeapotForumBundle:Board:new }
    requirements:
        boardSlug: .+?

ForumEditBoardPermissions:
    pattern:  /{boardSlug}/edit/permissions/
    defaults: { _controller: TeapotForumBundle:Board:editPermissions }
    requirements:
        boardSlug: .+?

ForumTopicPin:
    pattern: /{boardSlug}/{topicSlug}/pin/
    defaults: { _controller: TeapotForumBundle:Topic:pin }
    requirements:
        boardSlug: .+?
        topicSlug: "[^\/]+"

ForumTopicLock:
    pattern: /{boardSlug}/{topicSlug}/lock/
    defaults: { _controller: TeapotForumBundle:Topic:lock }
    requirements:
        boardSlug: .+?
        topicSlug: "[^\/]+"

ForumTopicDelete:
    pattern: /{boardSlug}/{topicSlug}/delete/
    defaults: { _controller: TeapotForumBundle:Topic:delete }
    requirements:
        boardSlug: .+?
        topicSlug: "[^\/]+"

ForumTopicEdit:
    pattern: /{boardSlug}/{topicSlug}/t/edit/
    defaults: { _controller: TeapotForumBundle:Topic:edit }
    requirements:
        boardSlug: .+?
        topicSlug: "[^\/]+"

# Message Controller
ForumListMessagesByTopic:
    pattern: /{boardSlug}/{topicSlug}/t/
    defaults: { _controller: TeapotForumBundle:Message:list }
    requirements:
        boardSlug: .+?
        topicSlug: "[^\/]+"

ForumNewMessage:
    pattern: /{boardSlug}/{topicSlug}/new-message/
    defaults: { _controller: TeapotForumBundle:Message:new }
    requirements:
        boardSlug: .+?
        topicSlug: "[^\/]+"

ForumMessageEdit:
    pattern: /{boardSlug}/{topicSlug}/edit/{messageId}/
    defaults: { _controller: TeapotForumBundle:Message:edit }
    requirements:
        boardSlug: .+?
        topicSlug: "[^\/]+"
        messageId: \d+

ForumMessageFlag:
    pattern: /{boardSlug}/{topicSlug}/flag/{messageId}/
    defaults: { _controller: TeapotForumBundle:Message:flag }
    requirements:
        boardSlug: .+?
        topicSlug: "[^\/]+"
        messageId: \d+

ForumMessageDelete:
    pattern: /{boardSlug}/{topicSlug}/delete/{messageId}/
    defaults: { _controller: TeapotForumBundle:Message:delete }
    requirements:
        boardSlug: .+?
        topicSlug: "[^\/]+"
        messageId: \d+

ForumMessageStar:
    pattern: /{boardSlug}/{topicSlug}/star/{messageId}/
    defaults: { _controller: TeapotForumBundle:Message:star }
    requirements:
        boardSlug: .+?
        topicSlug: "[^\/]+"
        messageId: \d+

ForumMessageUnstar:
    pattern: /{boardSlug}/{topicSlug}/unstar/{messageId}/
    defaults: { _controller: TeapotForumBundle:Message:unstar }
    requirements:
        boardSlug: .+?
        topicSlug: "[^\/]+"
        messageId: \d+

# Topic Controller
ForumListLatestTopics:
    pattern: /
    defaults: { _controller: TeapotForumBundle:Topic:latest }

ForumEditBoard:
    pattern:  /{boardSlug}/edit/
    defaults: { _controller: TeapotForumBundle:Board:edit }
    requirements:
        boardSlug: .+?

ForumDeleteBoard:
    pattern:  /{boardSlug}/delete/
    defaults: { _controller: TeapotForumBundle:Board:delete }
    requirements:
        boardSlug: .+?

ForumMoveBoard:
    pattern:  /{boardSlug}/move/
    defaults: { _controller: TeapotForumBundle:Board:move }
    requirements:
        boardSlug: .+?

ForumNewTopic:
    pattern: /{boardSlug}/new-topic/
    defaults: { _controller: TeapotForumBundle:Topic:new }
    requirements:
        boardSlug: .+?

ForumListTopicsByBoard:
    pattern: /{boardSlug}/
    defaults: { _controller: TeapotForumBundle:Topic:list }
    requirements:
        boardSlug: .+?