exercise_html_purifier:
    default:
        HTML.AllowedCommentsRegexp: "/^start reply$|^start quote$|^end reply$|^end quote$/s"

parameters:
    teapot_user.user_service.class: Teapot\UserBundle\Service\UserService
    teapot_user.user_group_service.class: Teapot\UserBundle\Service\UserGroupService

    teapot_forum.board_service.class:        Teapot\ForumBundle\Service\BoardService
    teapot_forum.flag_service.class:         Teapot\ForumBundle\Service\FlagService
    teapot_forum.topic_service.class:        Teapot\ForumBundle\Service\TopicService
    teapot_forum.message_service.class:      Teapot\ForumBundle\Service\MessageService
    teapot_forum.message_star_service.class: Teapot\ForumBundle\Service\MessageStarService
    teapot_forum.moderation_service.class:   Teapot\ForumBundle\Service\ModerationService
    teapot_forum.main_service.class:         Teapot\ForumBundle\Service\MainService
    teapot_forum.path_service.class:         Teapot\ForumBundle\Service\PathService
    teapot_forum.user_stat_service.class:    Teapot\ForumBundle\Service\UserStatService

    teapot_forum.board_repository.class:         'TeapotForumBundle:Board'
    teapot_forum.flag_repository.class:          'TeapotForumBundle:Flag'
    teapot_forum.topic_repository.class:         'TeapotForumBundle:Topic'
    teapot_forum.message_repository.class:       'TeapotForumBundle:Message'
    teapot_forum.message_star_repository.class:  'TeapotForumBundle:MessageStar'
    teapot_forum.moderation_repository.class:    'TeapotForumBundle:Moderation'
    teapot_forum.user_stat_repository.class:     'TeapotForumBundle:UserStat'

    teapot_user.user_repository.class: 'TeapotUserBundle:User'
    teapot_user.user_group_repository.class: 'TeapotUserBundle:UserGroup'
    teapot_user.user_token_repository.class: 'TeapotUserBundle:UserToken'